-- Sow Now variety seed data — full UK variety database
-- Sources: DT Brown, Thompson & Morgan, Kings Seeds, RHS, Sarah Raven
-- Covers: tomato, potato, pepper, french_bean, sweetcorn, courgette,
--         pea, carrot, lettuce, strawberry, onion, cucumber, brassica,
--         beetroot, spinach, parsnip, leek, pumpkin
-- Apply with: npm run db:seed

INSERT OR IGNORE INTO varieties (
  id, crop_key, name, supplier,
  gdd_to_germinate_min, gdd_to_germinate_max,
  gdd_to_harvest_min, gdd_to_harvest_max,
  base_temp_c, days_to_harvest_min, days_to_harvest_max,
  start_indoors_weeks, sow_method, determinate, description, verified
) VALUES

-- ── Tomatoes ──────────────────────────────────────────────────────────────────
('tomato-gardeners-delight',   'tomato', 'Gardener''s Delight',  'Thompson & Morgan',
  100, 140,  950, 1100, 10.0, 65, 75,  8, 'indoor', 0,
  'Classic cherry tomato. Reliable cropper in UK conditions, sweet flavour. Indeterminate — stake and pinch out.', 1),
('tomato-sungold',             'tomato', 'Sungold F1',           'Thompson & Morgan',
  100, 140,  900, 1050, 10.0, 60, 70,  8, 'indoor', 0,
  'Orange cherry tomato. Very sweet, thin skin. Reliable even in poor summers. Indeterminate.', 1),
('tomato-moneymaker',          'tomato', 'Moneymaker',           'DT Brown',
  100, 140, 1000, 1200, 10.0, 70, 80,  8, 'indoor', 0,
  'Traditional British favourite. Medium fruit, consistent yield. Indeterminate.', 1),
('tomato-alicante',            'tomato', 'Alicante',             'DT Brown',
  100, 140,  980, 1150, 10.0, 68, 78,  8, 'indoor', 0,
  'Medium-sized, smooth-skinned. Good disease resistance. Indeterminate.', 1),
('tomato-ailsa-craig',         'tomato', 'Ailsa Craig',          'Kings Seeds',
  100, 140, 1000, 1200, 10.0, 70, 80,  8, 'indoor', 0,
  'Show-winning variety. Large, smooth fruit. Popular on allotments. Indeterminate.', 1),
('tomato-tigerella',           'tomato', 'Tigerella',            'Thompson & Morgan',
  100, 140,  950, 1100, 10.0, 65, 75,  8, 'indoor', 0,
  'Distinctive red and orange stripes. Tangy flavour. Indeterminate.', 1),
('tomato-golden-sunrise',      'tomato', 'Golden Sunrise',       'DT Brown',
  100, 140, 1000, 1200, 10.0, 70, 80,  8, 'indoor', 0,
  'Yellow-fruited. Mild sweet flavour. Good for northern UK. Indeterminate.', 1),
('tomato-shirley-f1',          'tomato', 'Shirley F1',           'Kings Seeds',
  100, 130,  950, 1100, 10.0, 65, 75,  8, 'indoor', 1,
  'Determinate. Heavy cropper. Good resistance to common diseases. Popular for greenhouse growing.', 1),
('tomato-super-marmande',      'tomato', 'Super Marmande',       'DT Brown',
  100, 140, 1050, 1300, 10.0, 75, 90,  8, 'indoor', 1,
  'Beefsteak type. Large, ribbed fruit. Needs warm summer — greenhouse recommended in northern UK.', 1),
('tomato-sweet-million-f1',    'tomato', 'Sweet Million F1',     'Thompson & Morgan',
  100, 140,  880, 1000, 10.0, 60, 70,  8, 'indoor', 0,
  'Prolific cherry tomato. Very sweet. One of the earliest to harvest. Indeterminate.', 1),
('tomato-tumbling-tom',        'tomato', 'Tumbling Tom',         'Thompson & Morgan',
  100, 140,  880, 1050, 10.0, 60, 70,  8, 'indoor', 1,
  'Compact trailing variety ideal for hanging baskets and containers. Red or yellow fruited.', 1),
('tomato-black-cherry',        'tomato', 'Black Cherry',         'Kings Seeds',
  100, 140,  950, 1100, 10.0, 65, 75,  8, 'indoor', 0,
  'Deep red-black cherry tomato. Rich complex flavour. Conversation piece in the garden.', 1),

-- ── Potatoes ─────────────────────────────────────────────────────────────────
('potato-charlotte',           'potato', 'Charlotte',            'DT Brown',
  NULL, NULL, 900, 1100, 7.0, 100, 120, NULL, 'direct', NULL,
  'Waxy salad potato. Second early. Excellent flavour, holds together when cooked. Very popular UK variety.', 1),
('potato-maris-piper',         'potato', 'Maris Piper',          'DT Brown',
  NULL, NULL, 1100, 1400, 7.0, 120, 140, NULL, 'direct', NULL,
  'UK''s most popular variety. Floury. Best for chips, roasties. Maincrop — needs full season.', 1),
('potato-king-edward',         'potato', 'King Edward',          'Thompson & Morgan',
  NULL, NULL, 1100, 1350, 7.0, 120, 140, NULL, 'direct', NULL,
  'Classic white floury maincrop. Great for roasting and mash. Needs good soil.', 1),
('potato-jersey-royal',        'potato', 'Jersey Royal',         'Kings Seeds',
  NULL, NULL,  800,  950, 7.0,  80, 100, NULL, 'direct', NULL,
  'Famous first early. Distinctive earthy flavour. Best eaten fresh. Not for storing.', 1),
('potato-desiree',             'potato', 'Desiree',              'DT Brown',
  NULL, NULL, 1050, 1300, 7.0, 110, 130, NULL, 'direct', NULL,
  'Red-skinned waxy maincrop. Versatile — good for boiling, baking, chips. Drought tolerant.', 1),
('potato-swift',               'potato', 'Swift',                'Thompson & Morgan',
  NULL, NULL,  750,  900, 7.0,  75,  90, NULL, 'direct', NULL,
  'First early. Very fast-maturing. Ideal for containers. Good in northern UK and short seasons.', 1),
('potato-nicola',              'potato', 'Nicola',               'Kings Seeds',
  NULL, NULL,  950, 1150, 7.0, 100, 120, NULL, 'direct', NULL,
  'Yellow-fleshed waxy salad type. Second early. Holds shape well — great for salads.', 1),
('potato-pink-fir-apple',      'potato', 'Pink Fir Apple',       'DT Brown',
  NULL, NULL, 1150, 1400, 7.0, 125, 145, NULL, 'direct', NULL,
  'Heritage knobbly waxy potato. Superb flavour. Maincrop. Worth the wait.', 1),
('potato-maris-peer',          'potato', 'Maris Peer',           'Kings Seeds',
  NULL, NULL,  900, 1050, 7.0, 100, 115, NULL, 'direct', NULL,
  'Waxy second early. Small, uniform tubers. Popular for salads and boiling whole.', 1),
('potato-rooster',             'potato', 'Rooster',              'DT Brown',
  NULL, NULL, 1100, 1350, 7.0, 120, 140, NULL, 'direct', NULL,
  'Red-skinned floury maincrop. Excellent for baking and wedges. Disease resistant.', 1),

-- ── Peppers ──────────────────────────────────────────────────────────────────
('pepper-sweet-california',    'pepper', 'California Wonder',    'DT Brown',
  150, 200, 1200, 1450, 10.0, 110, 130, 10, 'indoor', NULL,
  'Classic bell pepper. Large, blocky fruit. Greenhouse essential in UK.', 1),
('pepper-sweet-red-bull',      'pepper', 'Red Bull',             'Thompson & Morgan',
  150, 200, 1150, 1350, 10.0, 100, 120, 10, 'indoor', NULL,
  'Pointed sweet pepper. Turns red when ripe. Good yield in greenhouse.', 1),
('pepper-padron',              'pepper', 'Padrón',               'Thompson & Morgan',
  150, 200, 1100, 1300, 10.0,  95, 115, 10, 'indoor', NULL,
  'Spanish tapas pepper. Pick small and green for mild flavour, larger for heat. Prolific.', 1),
('pepper-sweet-banana',        'pepper', 'Sweet Banana',         'Kings Seeds',
  150, 200, 1050, 1250, 10.0,  90, 110, 10, 'indoor', NULL,
  'Long yellow sweet pepper. Milder than most. Good for cool UK summers in greenhouse.', 1),
('pepper-cayenne-long-slim',   'pepper', 'Cayenne Long Slim',    'DT Brown',
  150, 200, 1150, 1350, 10.0, 100, 120, 10, 'indoor', NULL,
  'Hot cayenne. Long thin red fruits. Prolific. Greenhouse recommended for UK.', 1),
('pepper-hungarian-hot-wax',   'pepper', 'Hungarian Hot Wax',    'Thompson & Morgan',
  150, 200, 1100, 1300, 10.0,  95, 115, 10, 'indoor', NULL,
  'Yellow to red wax pepper. Medium heat. More tolerant of cool conditions than most peppers.', 1),
('pepper-sweet-marconi',       'pepper', 'Sweet Marconi',        'Kings Seeds',
  150, 200, 1150, 1400, 10.0, 100, 125, 10, 'indoor', NULL,
  'Italian frying pepper. Large, elongated, very sweet. Excellent roasted.', 1),
('pepper-jalapeno',            'pepper', 'Jalapeño',             'DT Brown',
  150, 200, 1150, 1350, 10.0, 100, 120, 10, 'indoor', NULL,
  'Classic Mexican chilli. Medium heat. Thick walls, good for stuffing. Prolific cropper.', 1),

-- ── French Beans ─────────────────────────────────────────────────────────────
('french-bean-cobra',          'french_bean', 'Cobra',            'Kings Seeds',
  60, 100, 800, 950, 10.0, 65, 75, NULL, 'direct', NULL,
  'Climbing French bean. Long, stringless pods. Very heavy cropper. Excellent flavour.', 1),
('french-bean-blue-lake',      'french_bean', 'Blue Lake',        'DT Brown',
  60, 100, 820, 970, 10.0, 65, 75, NULL, 'direct', NULL,
  'Dwarf bush type. Round, stringless pods. Classic allotment variety. Good for freezing.', 1),
('french-bean-borlotto-firetongue', 'french_bean', 'Borlotti Firetongue', 'Thompson & Morgan',
  60, 100, 850, 1000, 10.0, 70, 80, NULL, 'direct', NULL,
  'Beautiful red-splashed pods. Eat young as green bean or leave to dry for borlotti beans.', 1),
('french-bean-safari',         'french_bean', 'Safari',           'Kings Seeds',
  60, 100, 780, 920, 10.0, 60, 70, NULL, 'direct', NULL,
  'Dwarf bush type. Thin, stringless pods. High yield. Good disease resistance.', 1),
('french-bean-climbing-purple-queen', 'french_bean', 'Purple Queen', 'Thompson & Morgan',
  60, 100, 800, 950, 10.0, 65, 75, NULL, 'direct', NULL,
  'Striking purple pods that turn green when cooked. Climbing type. Good flavour.', 1),
('french-bean-delinel',        'french_bean', 'Delinel',          'DT Brown',
  60, 100, 800, 950, 10.0, 60, 70, NULL, 'direct', NULL,
  'Dwarf. Fine, pencil-thin pods. Excellent flavour. Good disease resistance.', 1),

-- ── Sweetcorn ────────────────────────────────────────────────────────────────
('sweetcorn-swift-f1',         'sweetcorn', 'Swift F1',          'Kings Seeds',
  50, 100, 1300, 1500, 10.0, 75, 85, 4, 'indoor', NULL,
  'One of the earliest sweetcorn for UK growing. Sweet, tender cobs. Good in northern gardens.', 1),
('sweetcorn-earlibird-f1',     'sweetcorn', 'Earlibird F1',      'DT Brown',
  50, 100, 1280, 1480, 10.0, 72, 82, 4, 'indoor', NULL,
  'Extra early supersweet. Very tender. One of the best for shorter UK seasons.', 1),
('sweetcorn-lark-f1',          'sweetcorn', 'Lark F1',           'Thompson & Morgan',
  50, 100, 1350, 1550, 10.0, 78, 88, 4, 'indoor', NULL,
  'Supersweet F1. Full-size cobs, excellent flavour. Reliable in average UK summers.', 1),
('sweetcorn-northern-extra-sweet', 'sweetcorn', 'Northern Extra Sweet F1', 'Kings Seeds',
  50, 100, 1250, 1450, 10.0, 70, 80, 4, 'indoor', NULL,
  'Bred specifically for UK and northern European climates. Reliable in cool summers.', 1),
('sweetcorn-sundance-f1',      'sweetcorn', 'Sundance F1',       'DT Brown',
  50, 100, 1350, 1550, 10.0, 80, 90, 4, 'indoor', NULL,
  'Classic British favourite. Long, well-filled cobs. Consistent performer.', 1),

-- ── Courgette ────────────────────────────────────────────────────────────────
('courgette-defender-f1',      'courgette', 'Defender F1',       'Kings Seeds',
  50, 80, 700, 850, 10.0, 55, 65, 3, 'indoor', NULL,
  'Classic green courgette. Good resistance to cucumber mosaic virus. Very productive.', 1),
('courgette-astia-f1',         'courgette', 'Astia F1',          'Thompson & Morgan',
  50, 80, 680, 820, 10.0, 50, 60, 3, 'indoor', NULL,
  'Compact bush variety bred for pots and small spaces. Productive and attractive.', 1),
('courgette-yellow-fin',       'courgette', 'Yellow Fin',        'DT Brown',
  50, 80, 700, 850, 10.0, 55, 65, 3, 'indoor', NULL,
  'Bright yellow fruits. Mild flavour. Makes a colourful addition to the veg plot.', 1),
('courgette-patio-star-f1',    'courgette', 'Patio Star F1',     'Thompson & Morgan',
  50, 80, 670, 800, 10.0, 50, 60, 3, 'indoor', NULL,
  'Very compact. Ideal for containers and small gardens. Round, bright yellow fruits.', 1),
('courgette-romanesco',        'courgette', 'Romanesco',         'Kings Seeds',
  50, 80, 720, 870, 10.0, 58, 68, 3, 'indoor', NULL,
  'Italian heritage variety. Ridged, pale green fruits. Nutty flavour. Vigorous plant.', 1),
('courgette-black-forest-f1',  'courgette', 'Black Forest F1',   'DT Brown',
  50, 80, 700, 850, 10.0, 55, 65, 3, 'indoor', NULL,
  'Climbing courgette — saves space in small gardens. Dark green fruits. Unusual and productive.', 1),

-- ── Peas ─────────────────────────────────────────────────────────────────────
('pea-hurst-greenshaft',       'pea', 'Hurst Greenshaft',       'DT Brown',
  100, 150, 950, 1150, 4.0, 80, 95, NULL, 'direct', NULL,
  'Classic maincrop shelling pea. Long pods, up to 9 peas. Good disease resistance. RHS AGM.', 1),
('pea-kelvedon-wonder',        'pea', 'Kelvedon Wonder',        'Kings Seeds',
  100, 150, 900, 1100, 4.0, 70, 85, NULL, 'direct', NULL,
  'Early, compact variety. Suitable for early and maincrop sowings. Excellent flavour.', 1),
('pea-sugar-snap',             'pea', 'Sugar Snap',             'Thompson & Morgan',
  100, 150, 900, 1100, 4.0, 70, 80, NULL, 'direct', NULL,
  'Eat pods whole when young and sweet. Climbing type. Popular with children. Very productive.', 1),
('pea-mangetout-oregon',       'pea', 'Oregon Sugar Pod',       'DT Brown',
  100, 150, 880, 1080, 4.0, 68, 78, NULL, 'direct', NULL,
  'Flat mangetout pods, eat whole. Tall climbing variety. Prolific and sweet.', 1),
('pea-meteor',                 'pea', 'Meteor',                 'Kings Seeds',
  100, 150, 850, 1050, 4.0, 65, 75, NULL, 'direct', NULL,
  'Very early, compact dwarf. Can overwinter. Ideal for cold frames and early sowings.', 1),
('pea-ambassador',             'pea', 'Ambassador',             'Thompson & Morgan',
  100, 150, 950, 1150, 4.0, 80, 95, NULL, 'direct', NULL,
  'Heavy cropping maincrop. Long pods with 8-9 peas. Good mildew resistance.', 1),
('pea-shiraz',                 'pea', 'Shiraz',                 'Kings Seeds',
  100, 150, 900, 1100, 4.0, 72, 82, NULL, 'direct', NULL,
  'Purple-podded climbing pea. Beautiful in the garden. Pods turn green when cooked.', 1),

-- ── Carrots ──────────────────────────────────────────────────────────────────
('carrot-nantes-5',            'carrot', 'Nantes 5',            'DT Brown',
  120, 200, 1200, 1450, 7.0, 70, 85, NULL, 'direct', NULL,
  'Classic Nantes-type. Cylindrical, blunt-ended, smooth. Sweet flavour. Reliable and versatile.', 1),
('carrot-chantenay-red-cored', 'carrot', 'Chantenay Red Cored', 'Kings Seeds',
  120, 200, 1150, 1400, 7.0, 65, 80, NULL, 'direct', NULL,
  'Short, stump-rooted. Good for heavy or shallow soils. Sweet and tender. Stores well.', 1),
('carrot-autumn-king-2',       'carrot', 'Autumn King 2',       'DT Brown',
  120, 200, 1300, 1550, 7.0, 80, 100, NULL, 'direct', NULL,
  'Large, tapering roots. Good for storing through winter. Maincrop variety.', 1),
('carrot-amsterdam-forcing-3', 'carrot', 'Amsterdam Forcing 3', 'Thompson & Morgan',
  120, 200, 1100, 1300, 7.0, 60, 75, NULL, 'direct', NULL,
  'Early variety. Slim, cylindrical roots. Can be sown under cover from February.', 1),
('carrot-resistafly-f1',       'carrot', 'Resistafly F1',       'Kings Seeds',
  120, 200, 1200, 1450, 7.0, 70, 85, NULL, 'direct', NULL,
  'Good resistance to carrot fly. Nantes-type. Ideal where carrot fly is a problem.', 1),
('carrot-purple-haze-f1',      'carrot', 'Purple Haze F1',      'Thompson & Morgan',
  120, 200, 1200, 1450, 7.0, 70, 85, NULL, 'direct', NULL,
  'Striking deep purple skin with orange core. Sweet flavour. Conversation piece.', 1),
('carrot-parmex',              'carrot', 'Parmex',              'DT Brown',
  120, 200, 1100, 1300, 7.0, 60, 70, NULL, 'direct', NULL,
  'Round, golf-ball sized. Perfect for containers, window boxes, heavy soils.', 1),

-- ── Lettuce ──────────────────────────────────────────────────────────────────
('lettuce-little-gem',         'lettuce', 'Little Gem',         'DT Brown',
  50, 80, 580, 750, 4.0, 60, 70, NULL, 'either', NULL,
  'Compact, semi-cos type. Crisp, sweet hearts. Very popular UK variety. Bolt resistant.', 1),
('lettuce-butterhead-sangria', 'lettuce', 'Sangria',            'Kings Seeds',
  50, 80, 550, 720, 4.0, 55, 65, NULL, 'either', NULL,
  'Butterhead type with beautiful red-tipped outer leaves. Soft, buttery texture.', 1),
('lettuce-lollo-rossa',        'lettuce', 'Lollo Rossa',        'Thompson & Morgan',
  50, 80, 560, 730, 4.0, 55, 65, NULL, 'either', NULL,
  'Cut-and-come-again. Deeply frilled red leaves. Decorative in the garden and on the plate.', 1),
('lettuce-cos-romaine',        'lettuce', 'Cos / Romaine',      'DT Brown',
  50, 80, 600, 780, 4.0, 65, 75, NULL, 'either', NULL,
  'Upright, crisp cos lettuce. Ideal for Caesar salads. Stands well without bolting.', 1),
('lettuce-salad-bowl-green',   'lettuce', 'Salad Bowl',         'Kings Seeds',
  50, 80, 550, 700, 4.0, 50, 60, NULL, 'either', NULL,
  'Cut-and-come-again oak-leaf type. Harvest outer leaves for weeks. Green or red available.', 1),
('lettuce-webb-wonderful',     'lettuce', 'Webb''s Wonderful',  'DT Brown',
  50, 80, 600, 780, 4.0, 65, 75, NULL, 'either', NULL,
  'Traditional crisphead (iceberg) type. Dense, crunchy hearts. Good bolting resistance.', 1),
('lettuce-winter-density',     'lettuce', 'Winter Density',     'Thompson & Morgan',
  50, 80, 580, 750, 4.0, 60, 75, NULL, 'either', NULL,
  'Hardy semi-cos. Can be sown in autumn for overwintering under cover. Sweet and crisp.', 1),

-- ── Strawberry ───────────────────────────────────────────────────────────────
('strawberry-cambridge-favourite', 'strawberry', 'Cambridge Favourite', 'DT Brown',
  NULL, NULL, 220, 280, 5.0, 30, 40, NULL, 'direct', NULL,
  'Classic UK variety. Heavy crops of firm, juicy fruits. Mid-season. RHS AGM.', 1),
('strawberry-elsanta',         'strawberry', 'Elsanta',          'Thompson & Morgan',
  NULL, NULL, 210, 270, 5.0, 28, 38, NULL, 'direct', NULL,
  'Commercial favourite. Firm, sweet, glossy red fruits. Mid-season. Good flavour.', 1),
('strawberry-honeoye',         'strawberry', 'Honeoye',          'Kings Seeds',
  NULL, NULL, 200, 260, 5.0, 26, 36, NULL, 'direct', NULL,
  'Early season. Large, bright red fruits. Heavy cropper. Good for northern UK.', 1),
('strawberry-mara-des-bois',   'strawberry', 'Mara des Bois',    'Thompson & Morgan',
  NULL, NULL, 220, 290, 5.0, 30, 42, NULL, 'direct', NULL,
  'Perpetual fruiting — crops from June to October. Wild strawberry fragrance. Exceptional flavour.', 1),
('strawberry-flamenco',        'strawberry', 'Flamenco',         'DT Brown',
  NULL, NULL, 220, 290, 5.0, 30, 45, NULL, 'direct', NULL,
  'Perpetual (everbearing) variety. Crops from June to October. Good disease resistance.', 1),
('strawberry-symphony',        'strawberry', 'Symphony',         'Kings Seeds',
  NULL, NULL, 230, 290, 5.0, 32, 42, NULL, 'direct', NULL,
  'Late-season. Large, firm fruits. Good flavour. Extends the season beyond other varieties.', 1),

-- ── Onion ────────────────────────────────────────────────────────────────────
('onion-sturon',               'onion', 'Sturon',               'DT Brown',
  100, 150, 1000, 1200, 7.0, 100, 120, NULL, 'direct', NULL,
  'Popular globe onion from sets. Firm, globe-shaped bulbs. Good storage. Very reliable.', 1),
('onion-red-baron',            'onion', 'Red Baron',            'Thompson & Morgan',
  100, 150,  980, 1180, 7.0,  95, 115, NULL, 'direct', NULL,
  'Red-skinned from sets. Deep red throughout. Mild, sweet flavour. Good for salads.', 1),
('onion-hercules-f1',          'onion', 'Hercules F1',          'Kings Seeds',
  100, 150, 1050, 1250, 7.0, 105, 125,  8, 'indoor', NULL,
  'Large, uniform globe. Grown from seed. Good disease resistance. Excellent for storing.', 1),
('onion-spring-white-lisbon',  'onion', 'White Lisbon',         'DT Brown',
  100, 150,  600,  750, 7.0,  60,  70, NULL, 'direct', NULL,
  'Spring (salad) onion. Pull young for mild flavour. Can sow successionally.', 1),
('onion-red-karmen',           'onion', 'Red Karmen',           'Thompson & Morgan',
  100, 150,  980, 1180, 7.0,  95, 115, NULL, 'direct', NULL,
  'Red sets. Flat-globe bulbs with deep red colour throughout. Good bolting resistance.', 1),
('onion-ailsa-craig',          'onion', 'Ailsa Craig',          'Kings Seeds',
  100, 150, 1050, 1250, 7.0, 105, 125,  8, 'indoor', NULL,
  'Exhibition-size globe onion from seed. Can grow to enormous size. Mild flavour.', 1),

-- ── Cucumber ─────────────────────────────────────────────────────────────────
('cucumber-telegraph-improved', 'cucumber', 'Telegraph Improved', 'DT Brown',
  80, 120, 800, 980, 10.0, 60, 70,  4, 'indoor', NULL,
  'Classic long greenhouse cucumber. Smooth, dark green fruits. All-female F1 type.', 1),
('cucumber-marketmore',        'cucumber', 'Marketmore',         'Kings Seeds',
  80, 120, 820, 1000, 10.0, 65, 75,  4, 'indoor', NULL,
  'Ridge cucumber for outdoor growing. Reliable and productive. Good disease resistance.', 1),
('cucumber-burpless-tasty-green', 'cucumber', 'Burpless Tasty Green F1', 'Thompson & Morgan',
  80, 120, 790, 960, 10.0, 58, 68,  4, 'indoor', NULL,
  'Indoor/outdoor type. Thin skin, no bitterness. Prolific. Can also be grown outside in warm summers.', 1),
('cucumber-crystal-lemon',     'cucumber', 'Crystal Lemon',      'DT Brown',
  80, 120, 830, 1000, 10.0, 65, 75,  4, 'indoor', NULL,
  'Round, lemon-yellow fruits. Mild, crisp. Good for outdoor growing. Unusual variety.', 1),
('cucumber-mini-munch-f1',     'cucumber', 'Mini Munch F1',      'Thompson & Morgan',
  80, 120, 780, 950, 10.0, 55, 65,  4, 'indoor', NULL,
  'Baby cucumbers 7–9cm long. Excellent flavour. Ideal for lunchboxes. Very productive.', 1),
('cucumber-diva-f1',           'cucumber', 'Diva F1',            'Kings Seeds',
  80, 120, 800, 970, 10.0, 60, 70,  4, 'indoor', NULL,
  'Seedless, bitterskin-free. Can be grown outdoors. Good powdery mildew resistance.', 1),

-- ── Brassica (Cabbage / Kale / Brussels) ─────────────────────────────────────
('brassica-january-king',      'brassica', 'January King',      'DT Brown',
  80, 120, 1000, 1300, 5.0, 120, 150,  5, 'indoor', NULL,
  'Hardy winter cabbage. Tinged purple-red in frost. Excellent flavour after first frosts.', 1),
('brassica-calabrese-green-magic', 'brassica', 'Green Magic F1 Calabrese', 'Kings Seeds',
  80, 120,  700,  900, 5.0,  80,  95,  4, 'indoor', NULL,
  'Broccoli / calabrese. Dense, dark green heads. Sow spring-summer for summer-autumn harvest.', 1),
('brassica-red-drumhead',      'brassica', 'Red Drumhead',       'Thompson & Morgan',
  80, 120, 1000, 1250, 5.0, 115, 140,  5, 'indoor', NULL,
  'Red cabbage. Firm, solid heads. Can be stored for months. Makes excellent pickled cabbage.', 1),
('brassica-curly-kale-dwarf',  'brassica', 'Dwarf Green Curled Kale', 'DT Brown',
  80, 120,  900, 1200, 5.0, 100, 135,  5, 'indoor', NULL,
  'Hardy kale. Very cold tolerant — can harvest through winter. Nutritious and productive.', 1),
('brassica-brussels-brilliant', 'brassica', 'Brilliant F1 Brussels Sprout', 'Kings Seeds',
  80, 120, 1100, 1400, 5.0, 120, 150,  5, 'indoor', NULL,
  'F1 Brussels sprout. Firm, tasty buttons. Mildew resistant. Harvest from October.', 1),
('brassica-purple-sprouting',  'brassica', 'Purple Sprouting Broccoli', 'Thompson & Morgan',
  80, 120, 1100, 1400, 5.0, 120, 160,  5, 'indoor', NULL,
  'Sow in spring, harvest the following Feb-April. Overwintering brassica. Very popular UK crop.', 1),
('brassica-savoy-ormskirk',    'brassica', 'Savoy Ormskirk',     'DT Brown',
  80, 120, 1000, 1250, 5.0, 110, 140,  5, 'indoor', NULL,
  'Classic Savoy cabbage. Deeply crinkled, sweet flavour. Hardy — improved by frost.', 1),

-- ── Beetroot ─────────────────────────────────────────────────────────────────
('beetroot-boltardy',          'beetroot', 'Boltardy',          'DT Brown',
  100, 150, 900, 1100, 7.0, 90, 110, NULL, 'direct', NULL,
  'UK''s most popular beetroot. Smooth, round, deep red. Excellent bolt resistance — can sow early.', 1),
('beetroot-chioggia',          'beetroot', 'Chioggia',          'Thompson & Morgan',
  100, 150, 920, 1120, 7.0, 92, 112, NULL, 'direct', NULL,
  'Italian heritage variety. Beautiful candy-stripe interior. Milder, sweeter than regular beetroot.', 1),
('beetroot-golden',            'beetroot', 'Golden',            'Kings Seeds',
  100, 150, 920, 1120, 7.0, 92, 112, NULL, 'direct', NULL,
  'Golden yellow flesh. Sweet, earthy flavour. Does not bleed when cooked. Unusual and decorative.', 1),
('beetroot-cylindra',          'beetroot', 'Cylindra',          'DT Brown',
  100, 150, 950, 1150, 7.0, 95, 115, NULL, 'direct', NULL,
  'Long, cylindrical roots. Easy to slice uniformly. Good for pickling. High yield.', 1),
('beetroot-detroit-2',         'beetroot', 'Detroit 2',         'Thompson & Morgan',
  100, 150, 900, 1100, 7.0, 90, 110, NULL, 'direct', NULL,
  'Classic smooth, round variety. Good uniformity. Excellent for pickling and salads.', 1),
('beetroot-pablo-f1',          'beetroot', 'Pablo F1',          'Kings Seeds',
  100, 150, 880, 1080, 7.0, 88, 108, NULL, 'direct', NULL,
  'F1 hybrid. Very uniform, smooth round roots. Bolt resistant. Good raw or cooked.', 1),

-- ── Spinach ──────────────────────────────────────────────────────────────────
('spinach-medania',            'spinach', 'Medania',            'DT Brown',
  50, 80, 580, 750, 5.0, 55, 65, NULL, 'direct', NULL,
  'Reliable, productive variety. Good bolt resistance. Suitable for spring and autumn sowings.', 1),
('spinach-perpetual-leaf-beet', 'spinach', 'Perpetual Spinach (Leaf Beet)', 'Kings Seeds',
  50, 80, 600, 800, 5.0, 60, 80, NULL, 'direct', NULL,
  'Cut-and-come-again. Not true spinach but similar use. Much more bolt resistant. Crops for months.', 1),
('spinach-giant-winter',       'spinach', 'Giant Winter',       'Thompson & Morgan',
  50, 80, 600, 780, 5.0, 58, 75, NULL, 'direct', NULL,
  'Hardy winter variety. Sow August-September for overwintering harvest. Large, dark leaves.', 1),
('spinach-amazon-f1',          'spinach', 'Amazon F1',          'DT Brown',
  50, 80, 560, 720, 5.0, 52, 62, NULL, 'direct', NULL,
  'F1 hybrid. Dark green, upright plants. Good bolt resistance. Suitable for baby leaf or full size.', 1),
('spinach-chard-rainbow',      'spinach', 'Rainbow Chard',      'Thompson & Morgan',
  50, 80, 600, 800, 5.0, 60, 80, NULL, 'direct', NULL,
  'Colourful mix of red, yellow, white and pink stems. Mild flavour. Ornamental and productive.', 1),

-- ── Parsnip ──────────────────────────────────────────────────────────────────
('parsnip-tender-true',        'parsnip', 'Tender and True',    'DT Brown',
  150, 250, 1400, 1750, 7.0, 130, 170, NULL, 'direct', NULL,
  'Long, slender white roots. Excellent flavour. Free from canker. Traditional favourite.', 1),
('parsnip-hollow-crown',       'parsnip', 'Hollow Crown',       'Kings Seeds',
  150, 250, 1400, 1800, 7.0, 130, 175, NULL, 'direct', NULL,
  'Heritage variety. Long, tapering roots. Good flavour — improves after first frost.', 1),
('parsnip-gladiator-f1',       'parsnip', 'Gladiator F1',       'Thompson & Morgan',
  150, 250, 1350, 1700, 7.0, 125, 165, NULL, 'direct', NULL,
  'F1 hybrid. Very smooth roots, easy to peel. Good canker resistance. High yield.', 1),
('parsnip-javelin-f1',         'parsnip', 'Javelin F1',         'DT Brown',
  150, 250, 1350, 1700, 7.0, 125, 165, NULL, 'direct', NULL,
  'Smooth white roots, very uniform. Excellent canker resistance. Good in heavier soils.', 1),
('parsnip-white-gem',          'parsnip', 'White Gem',          'Kings Seeds',
  150, 250, 1400, 1750, 7.0, 128, 168, NULL, 'direct', NULL,
  'Wedge-shaped, smooth-skinned. Good flavour. Reliable and popular for allotments.', 1),

-- ── Leek ─────────────────────────────────────────────────────────────────────
('leek-musselburgh',           'leek', 'Musselburgh',          'DT Brown',
  100, 150, 1300, 1600, 5.0, 120, 150,  8, 'indoor', NULL,
  'Traditional hardy variety. Thick, long stems. Excellent winter hardiness. UK favourite.', 1),
('leek-autumn-giant-porvite',  'leek', 'Autumn Giant Porvite', 'Kings Seeds',
  100, 150, 1200, 1500, 5.0, 110, 140,  8, 'indoor', NULL,
  'Early to mid-season. Long, blanched stems. Milder flavour than winter varieties.', 1),
('leek-blue-solaise',          'leek', 'Bleu de Solaise',      'Thompson & Morgan',
  100, 150, 1350, 1650, 5.0, 125, 160,  8, 'indoor', NULL,
  'French heritage variety. Turns purple-blue in cold. Very winter hardy. Excellent flavour.', 1),
('leek-carentan',              'leek', 'Carentan',             'DT Brown',
  100, 150, 1300, 1600, 5.0, 120, 150,  8, 'indoor', NULL,
  'Short, thick stems. Very hardy. Traditional market garden variety. Good storage.', 1),
('leek-hannibal-f1',           'leek', 'Hannibal F1',          'Kings Seeds',
  100, 150, 1200, 1500, 5.0, 110, 140,  8, 'indoor', NULL,
  'F1 hybrid. Very uniform. Good rust resistance. Harvest autumn through to spring.', 1),

-- ── Pumpkin ──────────────────────────────────────────────────────────────────
('pumpkin-jack-o-lantern',     'pumpkin', 'Jack O'' Lantern',  'DT Brown',
  80, 120, 1100, 1350, 10.0, 100, 120,  3, 'indoor', NULL,
  'Classic orange pumpkin. Perfect for Halloween carving and soup. Good in most UK gardens.', 1),
('pumpkin-atlantic-giant',     'pumpkin', 'Atlantic Giant',    'Thompson & Morgan',
  80, 120, 1200, 1500, 10.0, 115, 140,  3, 'indoor', NULL,
  'Can grow to enormous sizes. The giant pumpkin. Needs rich soil and lots of water. Fun project.', 1),
('pumpkin-crown-prince',       'pumpkin', 'Crown Prince',      'Kings Seeds',
  80, 120, 1100, 1400, 10.0, 100, 130,  3, 'indoor', NULL,
  'Steel-blue skin, vivid orange flesh. Outstanding sweet flavour. Stores for months. RHS AGM.', 1),
('pumpkin-butternut-waltham',  'pumpkin', 'Waltham Butternut', 'DT Brown',
  80, 120, 1100, 1350, 10.0, 100, 120,  3, 'indoor', NULL,
  'Classic butternut squash. Sweet, nutty flesh. Excellent for roasting and soup. Stores well.', 1),
('pumpkin-uchiki-kuri',        'pumpkin', 'Uchiki Kuri',       'Thompson & Morgan',
  80, 120, 1050, 1300, 10.0,  95, 115,  3, 'indoor', NULL,
  'Onion-shaped, bright orange skin. Rich, chestnut-like flavour. One of the most popular squash in UK.', 1),
('pumpkin-acorn-table-ace',    'pumpkin', 'Table Ace Acorn',   'Kings Seeds',
  80, 120, 1000, 1250, 10.0,  90, 110,  3, 'indoor', NULL,
  'Dark green acorn squash. Sweet, nutty flesh. Small enough for one serving. Very productive.', 1);
